### ISSUE TITLE
Support for single digit days of the month

### ISSUE THREAD

**Issue by UnConundrum** [sergey-chechaev/dates_from_string#2]
Is it possible to add support for single digit days of the month that don't have a leading 0?, such as "3/13/2017" in addition to "03/13/2017" ?

**Comment by sergey-chechaev** [comment]
Yes, it is possible, I will add support @UnConundrum.

**Comment by sergey-chechaev** [comment]
I add support for singl digit days:

```
DatesFromString.new.find_date("3/10/2017")
=> ["2017-10-3"]
```
